### PR TITLE
Added modules package dep

### PR DESCRIPTION
**Pull request by gwendall**
Fixes https://github.com/meteor-useraccounts/flow-routing/issues/35

### CODE REVIEW

**Comment by filipstachura** [comment]
Any plans on getting this into master?

**Comment by przytu1** [comment]
Hello, any updates?

**Comment by JulianKingman** [comment]
Can this be merged?

**Comment by IAMPetro** [comment]
It would be very helpful to get this fix merged into master :) i've been struggling with the boiler template because of the 1.14.2 bug.

**Pull request merged**
